USE [master]
GO

/****** Object:  Database [dbEventPlanner]    Script Date: 9/21/2023 1:23:25 AM ******/
CREATE DATABASE [dbEventPlanner]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbEventPlanner', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbEventPlanner.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbEventPlanner_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbEventPlanner_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbEventPlanner].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbEventPlanner] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbEventPlanner] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbEventPlanner] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbEventPlanner] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbEventPlanner] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbEventPlanner] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbEventPlanner] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbEventPlanner] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbEventPlanner] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbEventPlanner] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbEventPlanner] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbEventPlanner] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbEventPlanner] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbEventPlanner] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbEventPlanner] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbEventPlanner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbEventPlanner] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbEventPlanner] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbEventPlanner] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbEventPlanner] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbEventPlanner] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbEventPlanner] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbEventPlanner] SET RECOVERY FULL 
GO

ALTER DATABASE [dbEventPlanner] SET  MULTI_USER 
GO

ALTER DATABASE [dbEventPlanner] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbEventPlanner] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbEventPlanner] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbEventPlanner] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbEventPlanner] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbEventPlanner] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dbEventPlanner] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbEventPlanner] SET  READ_WRITE 
GO


