//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEventPlannerEntities : DbContext
    {
        public dbEventPlannerEntities()
            : base("name=dbEventPlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBookingDetail> tbBookingDetails { get; set; }
        public virtual DbSet<tbBookingVenue> tbBookingVenues { get; set; }
        public virtual DbSet<tbCity> tbCities { get; set; }
        public virtual DbSet<tbCountry> tbCountries { get; set; }
        public virtual DbSet<tbEventType> tbEventTypes { get; set; }
        public virtual DbSet<tbRole> tbRoles { get; set; }
        public virtual DbSet<tbState> tbStates { get; set; }
        public virtual DbSet<tbVenue> tbVenues { get; set; }
        public virtual DbSet<tbFood> tbFoods { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tbRegistration> tbRegistrations { get; set; }
        public virtual DbSet<tbEventsTodo> tbEventsTodoes { get; set; }
    }
}
