//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBookingVenue
    {
        public int BookingVenueID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public Nullable<int> GuestCount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> BookingID { get; set; }
    }
}
