//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBookingDetail
    {
        public int BookingId { get; set; }
        public string BookingNo { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string BookingApproval { get; set; }
        public Nullable<System.DateTime> BookingApprovalDate { get; set; }
        public string BookingCompletedFlag { get; set; }
    }
}
