//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFood
    {
        public int FoodID { get; set; }
        public string FoodType { get; set; }
        public string MealType { get; set; }
        public Nullable<int> DishType { get; set; }
        public string FoodName { get; set; }
        public string FoodFileName { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> FoodCost { get; set; }
    }
}
